# Required
version: 2
mkdocs:
  configuration: mkdocs.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
   version: 3.6
   install:
   - requirements: requirements.txt