services:
  docs:
    build: .
    volumes:
      - ./:/srv
    ports:
      - 8000:8000
    # uncomment this to simulate the production webserver
    # environment:
    #   - APP_TAG=production
    entrypoint: ["/bin/sh", "/srv/entrypoint.sh"]