site_name: Philly Community Wireless Docs
site_url: https://docs.phillycommunitywireless.org

theme:
  name: material
  language: en
  logo: assets/icons/logo.svg
  favicon: assets/icons/favicon/favicon.ico
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.sections
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Installations: Instalaciones
            Installation Overview: Descripción general
            Building Assessment: Evaluación del edificio
            Hardware: Hardware
            Solar Mesh Nodes: Nodos solares
            Device Configuration: Configuración de dispositivos
            Set a Static IP Address: Configurar una IP estática
            Configure EdgeRouter X: Configurar EdgeRouter X
            Configure Unifi APs: Configurar APs Unifi
            Configure IoT Devices: Configurar dispositivos IoT
            Troubleshoot Devices: Solución de problemas
            Resources: Recursos

nav:
  - Home: index.md
  
  - For Property Owners:
    - Installation Overview: installations/installations.md
    - Building Assessments: installations/buildingassessment.md

  - For Volunteers:
    - Installations:
      - Install Handbook for Volunteers: "Install Handbook for Volunteers" 
      - Hardware: installations/hardware.md
      - Solar Mesh Nodes: installations/solar.md
    - Device Configuration:
        - Set a Static IP Address: device-configuration/configure-computer.md
        - Configure routers running EdgeOS: 
          - Manual configuration: device-configuration/configure-edgerouter-x.md
          - Automated configuration with Ansible: "Automated configuration with Ansible"  
        - Configure Unifi APs: device-configuration/configure-ap-mesh.md
        - Wireless settings: Wireless settings
        - Troubleshoot Unifi Devices: device-configuration/troubleshoot-devices.md
    - Software:
      - Network Monitoring:
        - Unpoller: "Unpoller"
      - Useful Software: useful software

  - For network users: 
    - Troubleshoot your connection: "Troubleshoot your connection"
    - Configure IoT Devices: device-configuration/configure-IoT.md
    - "FAQs": "FAQs"

  - Resources: resources.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
