---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  exclude: assets
upload_dir: docs/assets/images
public_path: "/en/latest/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: site
  install_dependencies_command: python3 -m pip install -r requirements.txt
  preview_docker_image: python:3
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: echo "This is the build command"
